import './globals.css';
import '@radix-ui/themes/styles.css';

import { Theme, Container } from '@radix-ui/themes';
import type { Metadata } from 'next';
// eslint-disable-next-line camelcase
import { Geist, Geist_Mono } from 'next/font/google';

import BrandBanner from '@components/brandBanner/BrandBanner';

import AppHeader from '../_components/header/Header';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

const RootLayout = ({
  children
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Theme>
          <AppHeader />
          <Container>
            <div className="flex flex-col justify-center mx-auto">
              <BrandBanner />
              <div className="flex">{children}</div>
            </div>
          </Container>
        </Theme>
      </body>
    </html>
  );
};

export default RootLayout;
