import './globals.css';
import '@radix-ui/themes/styles.css';

import { Theme } from '@radix-ui/themes';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import AppHeader from '../_components/header/Header';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Theme>
          <AppHeader />
          <div className="flex justify-center items-center min-h-screen">
            <div className="flex w-2/3">{children}</div>
          </div>
        </Theme>
      </body>
    </html>
  );
}
