import './globals.css';
import '@radix-ui/themes/styles.css';

import { Theme } from '@radix-ui/themes';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import AppHeader from '../_components/header/Header';
import LogoBanner from '@/_components/logoBanner/LogoBanner';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Theme>
          <AppHeader />
          <div className="flex flex-col w-2/3 justify-center mx-auto">
            <LogoBanner />
            <div className="flex">{children}</div>
          </div>
        </Theme>
      </body>
    </html>
  );
}
